version: 4
updates:
  - package-ecosystem: "yarn" 
    directory: "/server" 
    schedule:
      interval: "daily"

version: 4
updates:
  - package-ecosystem: "yarn"
    directory: "/dinrestaurang"
    schedule:
      interval: "daily"


version: 4
updates:
  - package-ecosystem: "yarn" 
    directory: "/adminpanel"
    schedule:
      interval: "daily"
