version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/server" 
    schedule:
      interval: "monthly"

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/dinrestaurang"
    schedule:
      interval: "monthly"


version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/adminpanel"
    schedule:
      interval: "monthly"
