services:
  db:
    image: mysql
    container_name: din_restaurang_db
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: din_restaurang_db
      MYSQL_USER: fadi
      MYSQL_PASSWORD: '0000'
    env_file:
      - ./server/.docker.env
    volumes:
      - din_restaurang_db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: din_restaurang_db_admin
    ports:
      - 8080:80
    restart: unless-stopped
    volumes:
      - din_restaurang_db-admin:/var/lib/mysql

  api:
    build: ./server
    container_name: din_restaurang_backend
    ports:
      - 5000:5000
    env_file:
      - ./server/.docker.env
    volumes:
      - ./server:/backend
      - /backend/node_modules
    restart: unless-stopped
    links:
      - db

  web:
    build: ./dinrestaurang
    container_name: din_restaurang
    ports:
      - 3000:3000
    env_file:
      - ./dinrestaurang/.docker.env
    volumes:
      - ./dinrestaurang:/dinrestaurang
      - /dinrestaurang/node_modules
    restart: unless-stopped
    links:
      - api

  web2:
    build: ./adminpanel
    container_name: din_restaurang_adminpanel
    ports:
      - 3001:3001
    env_file:
      - ./adminpanel/.docker.env
    volumes:
      - ./adminpanel:/adminpanel
      - /adminpanel/node_modules
    restart: unless-stopped
    links:
      - api

volumes:
  din_restaurang_db-data:
  din_restaurang_db-admin:
