services:
  db:
    image: mysql:latest
    container_name: din_restaurang_db
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: din_restaurang_db
      MYSQL_USER: fadi
      MYSQL_PASSWORD: '0000'
    volumes:
      - din_restaurang_db-data:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: din_restaurang_db_admin
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - din_restaurang_db-admin:/var/lib/mysql

  api:
    build: ./server
    container_name: din_restaurang_backend
    ports:
      - 5000:5000
    env_file:
      - ./server/.env.prod
    restart: unless-stopped
    links:
      - db

  web:
    build: ./dinrestaurang
    container_name: din_restaurang
    ports:
      - 3000:3000
    env_file:
      - ./dinrestaurang/.env.prod
    restart: unless-stopped
    links:
      - api

  web2:
    build: ./adminpanel
    container_name: din_restaurang_adminpanel
    ports:
      - 3001:3000
    env_file:
      - ./adminpanel/.env.prod
    restart: unless-stopped
    links:
      - api

volumes:
  din_restaurang_db-data:
  din_restaurang_db-admin:
